### PR TITLE
fix: update list_indices to report if an index is vector or scalar

### LINKED ISSUE #1677: `list_indices` describes scalar index as `Vector` type
```
In [51]: ds.list_indices()
Out[51]:
[{'name': 's_idx',
  'type': 'Vector',
  'uuid': 'a962894c-0cb4-49f7-80fd-344dc6cdd2a0',
  'fields': ['s'],
  'version': 6,
  'fragment_ids': {0}},
 {'name': 'vec_idx',
  'type': 'Vector',
  'uuid': '9aa1516e-2d2b-4dd9-be6e-d7a7e2e8071b',
  'fields': ['vec'],
  'version': 7,
  'fragment_ids': {0}}]

In [52]: ds.schema
Out[52]:
s: string
vec: fixed_size_list<item: float>[128]
  child 0, item: float
```

### PR DESCRIPTION
**Pull request by westonpace**
Closes #1677

### CODE REVIEW

File: python/src/dataset.rs [hunk 1]
```diff
@@ -232,8 +232,21 @@ impl Dataset {
...
                 let schema = self_.ds.schema();
-                let field_names = schema
-                    .project_by_ids(idx.fields.as_slice())
+
+                let idx_schema = schema.project_by_ids(idx.fields.as_slice());
+
+                let is_vector = idx_schema
+                    .fields
+                    .iter()
+                    .any(|f| matches!(f.data_type(), DataType::FixedSizeList(_, _)));
```
Comment (westonpace) [inline python/src/dataset.rs:241]: We don't actually record the index type in the dataset metadata. Currently, we have to try loading the index to determine if it is scalar or vector.

However, looking at the field types should be accurate today.

**Review by chebbyChefNEQ — APPROVED** [review]
