### PR TITLE
fix: take and search now work properly with deletions

### LINKED ISSUE #1112: Take doesn't work with deletions
Right now, you can supply indices to the `take()` method, and it will return a record batch exactly equal in length to the input indices. To implement this, we map those indices to internal row ids. However, with deletions, these internal row ids might have holes in them, and so now we might return fewer rows than requested.

The current take implementation doesn't expect this, and will crash if there are deletions. However, we want to maintain the property that `take()` returns exactly the number of requested rows. So to solve this, we need to adjust the mapping of index to row id so that it skips the deleted row ids.

### PR DESCRIPTION
**Pull request by wjones127**
Closes #1112

Fixes several bugs related to deletions in take and vector search. This includes:

* `Fragment.take()` previously would return fewer rows than requested if there are deleted rows. Now the method will map the indices to valid row ids (skipping deleted rows), and will always return exactly the number of rows requested. The docs are also updated to describe this desired behavior so we can avoid the confusion in the future.
* `Dataset.take_rows()` now works even if there are deletions. Previously it was built assuming that running `take()` (now `take_rows()`) on a fragment would return exactly the number of rows requested, which isn't guaranteed if there are deletions. `take_rows()` has been modified to return `_rowid` so we can reconstruct the requested order in `Dataset.take_rows()`.
* `VectorIndex` is cached and re-used between versions of a dataset. However, it contained `LruDeletionVectorStore`, which had a reference to a particular manifest. This caused queries to be wrong because they were using cached deletion vectors from a different version of the dataset. The `LruDeletionVectorStore` was removed and replaced with the `FileMetadataCache` in `Session`. More importantly, the session is now passed down for each query as `PreFilter`, so the indices can be safely cached and reused across multiple versions of the dataset.

### CODE REVIEW

File: rust/src/index/prefilter.rs [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+use std::sync::Arc;
+
+use futures::stream::BoxStream;
+use futures::StreamExt;
+
+use crate::error::Result;
+use crate::Dataset;
+
+/// Filter out row ids that we know are not relevant to the query. This currently
+/// is just deleted rows.
```
Comment (wjones127) [inline rust/src/index/prefilter.rs:30]: FYI in the future I hope to re-use this struct to also do fragment-level pruning based on statistics.

File: rust/src/io/reader.rs [hunk 2]
```diff
@@ -462,19 +469,20 @@ async fn read_batch(
...
     };
 
+    // TODO: This is a minor cop out. Pushing deletion vector in to the decoders is hard
+    // so I'm going to just leave deletion filter at this layer for now.
+    // We should push this down futurther when we get to statistics-based predicate pushdown
+    let deletion_mask =
+        deletion_vector.and_then(|v| v.build_predicate(row_ids.as_ref().unwrap().iter()));
+
     if with_row_id {
-        let row_id_arr = Arc::new(UInt64Array::from(row_ids.clone().unwrap()));
```
Comment (wjones127) [inline rust/src/io/reader.rs:466]: I just pulled this up to eliminate the clone.

File: rust/src/index/prefilter.rs [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+        let local_row_id = row_id as u32;
+        Ok(!deletion_vector.contains(local_row_id))
+    }
+
+    /// Check whether a slice of row ids should be included in a query.
+    ///
+    /// Returns a vector of indices into the input slice that should be included,
+    /// also known as a selection vector.
+    pub async fn filter_row_ids(&self, row_ids: &[u64]) -> Result<Vec<u64>> {
+        // Group by the fragment id so we reduce mutex contention on the cache.
```
Comment (chebbyChefNEQ) [inline rust/src/index/prefilter.rs:56]: should we consider using `moka` for the fragment metadata cache? `moka` has async cache and is lockless.

File: rust/src/index/prefilter.rs [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+            .buffer_unordered(num_cpus::get())
+            .boxed();
+
+        let mut selection_vector = Vec::new();
+        while let Some(res) = stream.next().await {
+            let selection = res?;
+            selection_vector.extend(selection);
+        }
+
+        selection_vector.sort();
```
Comment (chebbyChefNEQ) [inline rust/src/index/prefilter.rs:96]: uber nit: `filter_row` "feels" like something that should be `O(N)`. maybe we should let the caller decide if the sort is necessary.

**Review by chebbyChefNEQ — APPROVED** [review]

File: rust/src/index/prefilter.rs (hunk 3 above)
Comment (wjones127) [reply rust/src/index/prefilter.rs:56]: Yeah that's a good idea.

File: rust/src/index/prefilter.rs (hunk 4 above)
Comment (wjones127) [reply rust/src/index/prefilter.rs:96]: Actually I probably can just make this O(N) by writing something like:

```rust
let deletion_vector_map: HashMap<u32, Arc<DeletionVector>> = todo!()

let selection_vector = row_ids.iter().enumerate().filter_map(|(i, row_id)| {
    let fragment_id = (row_id >> 32) as u32;
    let local_row_id = row_id as u32;
    if deletion_vector_map.get(fragment_id).unwrap().contains(local_row_id) {
        None
    } else {
        Some(i as u64)
    }
}).collect::Vec<u64>();
```
