### PR TITLE
fix: ensure query plans are correct

### LINKED ISSUE #1780: Prefilter with scalar index does not seem to filter flat side
To reproduce:

1. Create a table with a vector and metadata column
2. Create a scalar index on metadata column
3. Create a vector index on vector column
4. Insert new data into table
5. Search with prefilter that shouldn't be satisfied by any row

Even filters that should exclude everything are returning rows that don't match the filter.

<details><summary>Reproduction</summary>
<p>

```python
import lance
import pyarrow as pa
import pyarrow.compute as pc

ndims = 128
nrows = 1000

tab = pa.table({
    "a": pa.array(range(nrows), type=pa.int64()),
    "vec": pa.FixedSizeListArray.from_arrays(pc.random(nrows * ndims).cast(pa.float32()), ndims),
})

ds = lance.write_dataset(tab, "test")
ds.create_scalar_index("a", index_type="BTREE")
ds.create_index("vec", index_type="IVF_PQ", num_partitions=100, num_sub_vectors=32)
ds = lance.write_dataset(tab, "test", mode="append")

ds.to_table(filter="a < 0", prefilter=True, nearest=dict(column="vec", q=pc.random(ndims).cast(pa.float32()), k=10))
```

```
pyarrow.Table
a: int64
vec: fixed_size_list<item: float>[128]
  child 0, item: float
_distance: float
----
a: [[225,724,815,763,836,492,468,641,255,579]]
vec: [[[0.25368625,0.19733237,0.3912018,0.49899265,0.6610746,...,0.9062147,0.35503843,0.15168831,0.39380872,0.7218188],[0.65825766,0.59704685,0.3737649,0.77924085,0.095742375,...,0.6327833,0.0013947232,0.6931919,0.21587041,0.8569414],...,[0.57566106,0.42982322,0.2025612,0.81364477,0.76690024,...,0.5764657,0.6811421,0.38438603,0.8658503,0.5233506],[0.8746555,0.56286657,0.93941736,0.44651106,0.88239384,...,0.59397054,0.23659194,0.049441166,0.8146435,0.7444599]]]
_distance: [[15.909677,16.21813,16.683304,16.724335,17.212389,17.333723,17.567865,17.723175,17.985935,18.08932]]
```
</p>
</details>

### PR DESCRIPTION
**Pull request by wjones127**
This holds several bug fixes and refactors:

* Adds initial physical optimizer rules in lead up to #1782. I've noted further optimization passes we could write in the future.
* Fixes #1780
* Fixes issue where TakeExec was done twice in a row for Flat KNN queries.
* Fixes issue where scalar indices were being ignored for scans.
* Simplifies and expands test suite for the scanner `create_plan()` method.

This is a test footer.

### CODE REVIEW

File: rust/lance/src/dataset/scanner.rs [hunk 1]
```diff
@@ -643,7 +652,7 @@ impl Scanner {
     async fn create_plan(&self) -> Result<Arc<dyn ExecutionPlan>> {
         // Scalar indices are only used when prefiltering
         // TODO: Should we use them when postfiltering if there is no vector search?
-        let use_scalar_index = self.prefilter;
+        let use_scalar_index = self.prefilter || self.nearest.is_none();
```
Comment (wjones127) [inline rust/lance/src/dataset/scanner.rs:655]: This condition was preventing scalar indices from being used in scans.

File: rust/lance/src/dataset/scanner.rs [hunk 2]
```diff
@@ -927,10 +942,11 @@ impl Scanner {
...
             );
-            if let Some(refine_expr) = filter_plan.refine_expr.as_ref() {
+
+            if let Some(expr) = filter_plan.full_expr.as_ref() {
                 // If there is a prefilter we need to manually apply it to the new data
                 let planner = Planner::new(scan_node.schema());
-                let physical_refine_expr = planner.create_physical_expr(refine_expr)?;
+                let physical_refine_expr = planner.create_physical_expr(expr)?;
                 scan_node = Arc::new(FilterExec::try_new(physical_refine_expr, scan_node)?);
             }
```
Comment (wjones127) [inline rust/lance/src/dataset/scanner.rs:951]: This was the fix for the filter not being applied. We were totally skipping the non-refine part of the `FilterPlan` for the fragments not covered by the vector index.

File: rust/lance-core/src/datatypes/schema.rs [hunk 3]
```diff
@@ -113,7 +113,19 @@ impl Schema {
...
+        // Check for duplicate field ids
+        let mut seen_ids = HashSet::new();
+        for field in self.fields_pre_order() {
+            if !seen_ids.insert(field.id) {
+                return Err(Error::Schema {
+                    message: format!("Duplicate field id {} in schema {:?}", field.id, self),
+                    location: location!(),
+                });
+            }
+        }
```
Comment (westonpace) [inline rust/lance-core/src/datatypes/schema.rs:126]: How would this happen?  Or is this just a sanity check?

File: rust/lance/src/dataset/scanner.rs (hunk 1 above)
Comment (westonpace) [reply rust/lance/src/dataset/scanner.rs:655]: Why do we want to do that?

File: rust/lance/src/io/exec/knn.rs [hunk 4]
```diff
@@ -425,7 +425,12 @@ impl DisplayAs for KNNIndexExec {
     fn fmt_as(&self, t: DisplayFormatType, f: &mut std::fmt::Formatter) -> std::fmt::Result {
         match t {
             DisplayFormatType::Default | DisplayFormatType::Verbose => {
-                write!(f, "KNNIndex: name={}, k={}", self.index.uuid, self.query.k)
+                write!(
+                    f,
+                    "KNNIndex: name={}, k={}",
+                    self.index.uuid,
+                    self.query.k * self.query.refine_factor.unwrap_or(1) as usize
```
Comment (westonpace) [inline rust/lance/src/io/exec/knn.rs:432]: I get what you are after but this might be slightly confusing since `k` is used elsewhere.  Maybe change `k={}` to `num_rows={}`?

File: rust/lance/src/io/exec/optimizer.rs [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+    common::tree_node::{Transformed, TreeNode},
+    config::ConfigOptions,
+    error::Result as DFResult,
+    physical_optimizer::PhysicalOptimizerRule,
+    physical_plan::ExecutionPlan,
+};
+
+use super::TakeExec;
+
+/// Rule that eliminates [TakeExec] nodes that are immediately followed by another [TakeExec].
```
Comment (westonpace) [inline rust/lance/src/io/exec/optimizer.rs:29]: Wouldn't this be an invalid input plan?  Doesn't `TakeExec` need row ids as input?  It doesn't output row ids does it?

**Review by westonpace — APPROVED** [review]
Just minor questions / comments.  Thanks for updating the tests!

File: rust/lance/src/dataset/scanner.rs (hunk 1 above)
Comment (wjones127) [reply rust/lance/src/dataset/scanner.rs:655]: You think we shouldn't?

I was thinking a user might expect a query like:

```python
dataset.to_table(filter="id = 42")
```

To use a scalar index on `id` if it was available. But I suppose in other cases it might not be desirable, like if the filter isn't very selective. Is that what you are getting at?

File: rust/lance-core/src/datatypes/schema.rs (hunk 3 above)
Comment (wjones127) [reply rust/lance-core/src/datatypes/schema.rs:126]: Yeah this is just a sanity check. I was going to add a method `Schema::union(&self, other: &Schema)`, and needed to check we don't get duplicate field ids there. But I didn't end up needing that method. Still seems like something we should validate when we can.

File: rust/lance/src/io/exec/optimizer.rs (hunk 5 above)
Comment (wjones127) [reply rust/lance/src/io/exec/optimizer.rs:29]: It almost always outputs row ids. For example:

https://github.com/lancedb/lance/blob/ee1fb9aa8e4bd4989678588889ecc916211a6cd9/rust/lance/src/dataset/scanner.rs#L3350-L3353

File: rust/lance/src/io/exec/knn.rs (hunk 4 above)
Comment (wjones127) [reply rust/lance/src/io/exec/knn.rs:432]: I personally find it clear in-context of a plan:

https://github.com/lancedb/lance/blob/ee1fb9aa8e4bd4989678588889ecc916211a6cd9/rust/lance/src/dataset/scanner.rs#L3217-L3221

We see that originally k=40 and then later we take k=10 with exact, which is a good representation of what `refine_factor=4` means. TBH I was tempted to refactor `KNNIndex` to not have a `refine_factor` parameter and just have a `k` parameter that was set to the query `k * refine_factor`. `KNNIndex` shouldn't need to know about `refine_factor`.

Comment (westonpace) [reply rust/lance/src/io/exec/knn.rs:432]: Ok, I agree with that reasoning.

File: rust/lance/src/dataset/scanner.rs (hunk 1 above)
Comment (westonpace) [reply rust/lance/src/dataset/scanner.rs:655]: No, sorry, I was reading your statement backwards.  I thought you were disabling scalar indices.  I do think I need to add a "use_scalar_index" field soon though because you're right, there will be queries where the scalar index hurts rather than helps.

For now though, this change is good.
