### PR TITLE
fix: lance failed to encode 1025 rep/def values

### LINKED ISSUE #4466: fuzz: lance failed to encode 1025 rep/def 1025 values

### PR DESCRIPTION
**Pull request by Xuanwo**
fix #4466

---

Hi, @westonpace I'm not sure if this fix is correct. Maybe also related to my changes of https://github.com/lancedb/lance/pull/4440

### CODE REVIEW

File: rust/lance-encoding/src/encodings/logical/primitive.rs [hunk 1]
```diff
@@ -1358,8 +1358,27 @@ impl ChunkInstructions {
...
+                    // Only process if this chunk has a preamble we need
+                    if chunk.has_preamble && need_preamble {
+                        chunk_instructions.push(Self {
+                            chunk_idx: block_index,
+                            preamble: PreambleAction::Take,
+                            rows_to_skip: 0,
+                            rows_to_take: 0,
+                            take_trailer: false,
+                        });
+                        need_preamble = false;
```
Comment (westonpace) [inline rust/lance-encoding/src/encodings/logical/primitive.rs]: I think we can only set `need_preamble = false` if there is at least one row (`chunk.starts_including_trailer > 0`)  Otherwise, it is possible the chunk is entirely preamble in which case we need at least the entire chunk and the preamble from the next chunk.

File: rust/lance-encoding/src/encodings/logical/primitive.rs [hunk 2]
```diff
@@ -1358,8 +1358,27 @@ impl ChunkInstructions {
 
             while rows_needed > 0 || need_preamble {
                 let chunk = &rep_index.blocks[block_index];
-                let rows_avail = chunk.starts_including_trailer - to_skip;
-                debug_assert!(rows_avail > 0);
+                let rows_avail = chunk.starts_including_trailer.saturating_sub(to_skip);
+
+                // Handle blocks that are entirely preamble (rows_avail = 0)
+                // These blocks have no rows to take but may have a preamble we need
+                if rows_avail == 0 {
```
Comment (westonpace) [inline rust/lance-encoding/src/encodings/logical/primitive.rs]: I think this needs to be `rows_avail == 0 && to_skip == 0`.  If we need to skip even 1 row then we are not looking for the preamble.  That being said...I'm not sure if it is possible that `rows_avail == 0 && to_skip != 0` because otherwise we would have skipped the block in the binary search.  Still, might not hurt to be explicit.

**Review by westonpace — CHANGES_REQUESTED** [review]
Good find.  This chunk instruction code is always super confusing to me (and I wrote it :laughing:)

Marking `Request changes` since I think the comment about `need_preamble = false` will need to be addressed.

File: rust/lance-encoding/src/encodings/logical/primitive.rs (hunk 1 above)
Comment (Xuanwo) [reply rust/lance-encoding/src/encodings/logical/primitive.rs]: You are right, let me handle this.

File: rust/lance-encoding/src/encodings/logical/primitive.rs (hunk 2 above)
Comment (Xuanwo) [reply rust/lance-encoding/src/encodings/logical/primitive.rs]: Added an extra edge check.

File: rust/lance-encoding/src/encodings/logical/primitive.rs [hunk 3]
```diff
@@ -1357,9 +1357,49 @@ impl ChunkInstructions {
             let mut to_skip = user_range.start - rep_index.blocks[block_index].first_row;
 
             while rows_needed > 0 || need_preamble {
+                // Check if we've gone past the last block
+                if block_index >= rep_index.blocks.len() {
+                    break;
+                }
```
Comment (westonpace) [inline rust/lance-encoding/src/encodings/logical/primitive.rs]: Did you actually run into this?  I thought rows_needed couldn't be larger than the number of rows available?

File: rust/lance-encoding/src/encodings/logical/primitive.rs [hunk 4]
```diff
@@ -1357,9 +1357,49 @@ impl ChunkInstructions {
...
+                        });
+                        // Only set need_preamble = false if the chunk has at least one row
+                        // Otherwise, the chunk is entirely preamble and we need the next chunk's preamble too
+                        if chunk.starts_including_trailer > 0 {
+                            need_preamble = false;
+                        }
+                    }
+                    // Move to next block
+                    block_index += 1;
+                    to_skip = 0;
```
Comment (westonpace) [inline rust/lance-encoding/src/encodings/logical/primitive.rs]: This line is redundant (we have `to_skip == 0` above) but harmless.
```suggestion
```

**Review by westonpace — APPROVED** [review]
This logic is correct I believe

File: rust/lance-encoding/src/encodings/logical/primitive.rs (hunk 3 above)
Comment (Xuanwo) [reply rust/lance-encoding/src/encodings/logical/primitive.rs]: Yep, in our test we can hit a case where all blocks are preamble, and the `block_index` can larger than `rep_index.blocks.len()` after `block_index += 1`. I can merge this change with `chunk.starts_including_trailer > 0` to make it more clear like:

```diff
if chunk.has_preamble && need_preamble {
    chunk_instructions.push(...);

-    if chunk.starts_including_trailer > 0 {
+    if chunk.starts_including_trailer > 0 || block_index == rep_index.blocks.len() - 1 {
        need_preamble = false;
    }
}
```

Comment (Xuanwo) [reply rust/lance-encoding/src/encodings/logical/primitive.rs]: The test `encodings::logical::list::tests::test_fuzz_issue_4466` exactly failed on this case.

```
---- encodings::logical::list::tests::test_fuzz_issue_4466 stdout ----

thread 'encodings::logical::list::tests::test_fuzz_issue_4466' panicked at rust/lance-encoding/src/encodings/logical/primitive.rs:1365:46:
index out of bounds: the len is 2 but the index is 2
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    encodings::logical::list::tests::test_fuzz_issue_4466
```

File: rust/lance-encoding/src/encodings/logical/primitive.rs [hunk 5]
```diff
@@ -1357,9 +1357,48 @@ impl ChunkInstructions {
...
+                            preamble: PreambleAction::Take,
+                            rows_to_skip: 0,
+                            rows_to_take: 0,
+                            take_trailer: false,
+                        });
+                        // Only set need_preamble = false if the chunk has at least one row
+                        // Otherwise, the chunk is entirely preamble and we need the next chunk's preamble too
+                        if chunk.starts_including_trailer > 0 {
+                            need_preamble = false;
+                        }
```
Comment (westonpace) [inline rust/lance-encoding/src/encodings/logical/primitive.rs]:
```suggestion
                        if chunk.starts_including_trailer > 0
                            || block_index == rep_index.blocks.len() - 1
                        {
                            need_preamble = false;
                        }
```

File: rust/lance-encoding/src/encodings/logical/primitive.rs [hunk 6]
```diff
@@ -1357,9 +1357,48 @@ impl ChunkInstructions {
             let mut to_skip = user_range.start - rep_index.blocks[block_index].first_row;
 
             while rows_needed > 0 || need_preamble {
+                // Check if we've gone past the last block
+                if block_index >= rep_index.blocks.len() {
+                    break;
+                }
```
Comment (westonpace) [inline rust/lance-encoding/src/encodings/logical/primitive.rs]:
```suggestion
                // Check if we've gone past the last block (should not happen)
                if block_index >= rep_index.blocks.len() {
                    log::warn!("schedule_instructions inconsistency: block_index >= rep_index.blocks.len(), exiting early");
                    break;
                }
```

**Review by westonpace — APPROVED** [review]
Ok, you were right.  We need to set `needs_preamble = false` on the last block :laughing:
