### PR TITLE
fix: handle deletions in take

### LINKED ISSUE #3332: Can take API skip deleted rows?
scene:

```
import lance
import pyarrow as pa

schema = pa.schema([
    pa.field("id", pa.int32()),
    pa.field("data", pa.string())
])

data = [
    {"id": 1, "data": "test"},
    {"id": 2, "data": "testab"},
]

table = pa.Table.from_pylist(data, schema=schema)

ds = lance.write_dataset(table, "./alice_and_bob2.lance", mode="overwrite")
ds.delete("id == 1")
ds.take([0])
```

returns:

```
pyarrow.Table
id: int32
data: string
----
id: [[]]
data: [[]]
```

if:
```
ds.take([1])
```

returns:

```
OSError: Invalid user input: _rowaddr belongs to non-existent fragment: 18446744073709551615, xxx/lance/src/dataset/take.rs:130:17
```

## Questions:
* How to take the id == 2 row?
* Can we make a config option to skip delete rows when invoke take API?

Some research:

I saw there is a `take_range` [function](https://github.com/lancedb/lance/blob/39f12dc3af0d42d3a8ba420df42c7010babbf2e7/rust/lance/src/dataset/fragment.rs#L2056), which calls `do_read_range` and passes a default `false` for parameter `skip_deleted_rows`. 

@westonpace @eddyxu Could it be a configured option?

### PR DESCRIPTION
**Pull request by wjones127**
We were not properly handling deletions when mapping raw offsets to row addresses. This PR makes sure we use the deletion files to figure out the exact row addresses.

Fixes #3332

### CODE REVIEW

File: rust/lance/src/dataset/take.rs [hunk 1]
```diff
@@ -626,6 +643,55 @@ mod test {
...
+            max_rows_per_file: 40,
+            max_rows_per_group: 10,
+            ..Default::default()
+        };
+        let batches = RecordBatchIterator::new([Ok(data.clone())], data.schema());
+        let mut dataset = Dataset::write(batches, "memory://", Some(write_params))
+            .await
+            .unwrap();
+
+        dataset.delete("i in (40, 77, 78, 79)").await.unwrap();
```
Comment (yanghua) [inline rust/lance/src/dataset/take.rs:659]: Can we also test delete 0?

Comment (wjones127) [reply rust/lance/src/dataset/take.rs:659]: I can add a test for that. What is special about deleting zero?

Comment (yanghua) [reply rust/lance/src/dataset/take.rs:659]: just want to see if it works correctly e2e, due to we triggered a bug when `take(0)`.

File: rust/lance-core/src/utils/deletion.rs [hunk 2]
```diff
@@ -115,6 +123,64 @@ impl DeletionVector {
...
+impl OffsetMapper {
+    pub fn new(dv: Arc<DeletionVector>) -> Self {
+        Self {
+            dv,
+            left: 0,
+            last_diff: 0,
+        }
+    }
+
+    pub fn map_offset(&mut self, offset: u32) -> u32 {
```
Comment (yanghua) [inline rust/lance-core/src/utils/deletion.rs:155]: I see we also have a judgment in `fragement.rs` [here](https://github.com/lancedb/lance/blob/main/rust/lance/src/dataset/fragment.rs#L2053) (but missed the judgment of discrete offset). Can we find one way to converge these judgments into one place?

File: rust/lance/src/dataset/take.rs (hunk 1 above)
Comment (wjones127) [reply rust/lance/src/dataset/take.rs:659]: The condition you hit was there was a deletion at beginning of fragment. 40 is the beginning of the second fragment, which is why I chose that value.

**Review by yanghua — APPROVED** [review]
LGTM

File: rust/lance-core/src/utils/deletion.rs (hunk 2 above)
Comment (wjones127) [reply rust/lance-core/src/utils/deletion.rs:155]: I could probably re-implement that other function in terms of this one, if we wanted. Though not sure if it is worth while.
