### PR TITLE
fix: join job may cause inconsistent delta indices

### LINKED ISSUE #5312: Panic while optimizing vector indices
Getting large number of panics when optimizing vector indices:

```
thread 'main' panicked at 'index out of bounds: the len is 117 but the index is 117': /src/lance/rust/lance-index/src/vector/ivf/storage.rs:95
   0: log_panics::Config::install_panic_hook::{{closure}}
   1: indexer::install_panic_handler::{{closure}}
   2: std::panicking::panic_with_hook
   3: std::panicking::panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: __rustc::rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::panicking::panic_bounds_check
   8: <lance::index::vector::ivf::v2::IVFIndex<S,Q> as lance_index::vector::VectorIndex>::partition_size
   9: lance::index::vector::builder::IvfIndexBuilder<S,Q>::should_split
  10: lance::index::vector::builder::IvfIndexBuilder<S,Q>::build_partitions::{{closure}}
  11: lance::index::vector::builder::IvfIndexBuilder<S,Q>::build::{{closure}}
  12: lance::index::vector::ivf::optimize_vector_indices_v2::{{closure}}
  13: lance::index::vector::ivf::optimize_vector_indices::{{closure}}
  14: lance::index::<impl lance_index::traits::DatasetIndexExt for lance::dataset::Dataset>::optimize_indices::{{closure}}::{{closure}}
```

### PR DESCRIPTION
**Pull request by BubbleCal**
fix #5312 

- handle the case of delta indices have diff number of partitions, split/join will merge all delta indices into one
- trigger join on incremental indexing, not remap

### CODE REVIEW

File: rust/lance/src/index/vector.rs [hunk 1]
```diff
@@ -633,7 +633,7 @@ pub(crate) async fn build_vector_index_incremental(
                     shuffler,
                     (),
                     frag_reuse_index,
-                    OptimizeOptions::new(),
+                    OptimizeOptions::append(),
```
Comment (westonpace) [inline rust/lance/src/index/vector.rs]: Why is this change needed?

File: rust/lance-index/src/vector/ivf/storage.rs [hunk 2]
```diff
@@ -92,7 +92,7 @@ impl IvfModel {
     }
 
     pub fn partition_size(&self, part: usize) -> usize {
-        self.lengths[part] as usize
+        self.lengths.get(part).copied().unwrap_or_default() as usize
```
Comment (wkalt) [inline rust/lance-index/src/vector/ivf/storage.rs:95]: this will return a zero in the previous case that panicked. Is that a correct fix? Seems like zero would be an incorrect or unexpected result. What's the consequence of a zero return value?

File: rust/lance-index/src/vector/v3/shuffler.rs [hunk 3]
```diff
@@ -248,6 +248,10 @@ impl ShuffleReader for IvfShufflerReader {
         &self,
         partition_id: usize,
     ) -> Result<Option<Box<dyn RecordBatchStream + Unpin + 'static>>> {
+        if partition_id >= self.partition_sizes.len() {
+            return Ok(None);
+        }
```
Comment (wkalt) [inline rust/lance-index/src/vector/v3/shuffler.rs:253]: similar question here - is it a cause for concern that this function would be asked for an out of bounds partition? If so should this be an error?

File: rust/lance/src/index/vector/builder.rs [hunk 4]
```diff
@@ -1694,6 +1647,18 @@ impl<S: IvfSubIndex + 'static, Q: Quantization + 'static> IvfIndexBuilder<S, Q>
...
+            if part_idx >= index.ivf_model().num_partitions() {
+                // there was a bug that may cause delta indices have different number of partitions,
+                // it's safe to skip loading the extra partition, and split/join the existing partitions,
+                // split/join would merge all delta indices into one so it would fix the issue
+                // see https://github.com/lance-format/lance/issues/5312
+                log::warn!(
+                    "partition index is {} but the number of partitions is {}, skip loading it",
+                    part_idx,
+                    index.ivf_model().num_partitions()
+                );
```
Comment (wkalt) [inline rust/lance/src/index/vector/builder.rs:1661]: is it correct to think we'll see this in some cases initially but should not see it in the long term?

File: rust/lance-index/src/vector/ivf/storage.rs (hunk 2 above)
Comment (BubbleCal) [reply rust/lance-index/src/vector/ivf/storage.rs:95]: this gets the size of the given partition, say delta index A has 3 partitions and delta index B has 4 partitions, when we calculate the total partition size of 4-th partition, index A just returns 0, and this is correct because we can consider that index A has 4 partitions but the 4-th is empty.

and after the fix, we will merge all delta indices into one, so the `unwrap_or_default()` path will never be reached

File: rust/lance/src/index/vector/builder.rs (hunk 4 above)
Comment (BubbleCal) [reply rust/lance/src/index/vector/builder.rs:1661]: Yes, this is just for fixing the corrupted delta indices, after merging them, we will never reach these branches

File: rust/lance/src/index/vector/builder.rs [hunk 5]
```diff
@@ -1979,6 +1944,12 @@ enum ReassignPartition {
     ReassignCandidate(u32),
 }
 
+#[derive(Debug, Copy, Clone, PartialEq, Eq)]
+enum PartitionMaintain {
```
Comment (wjones127) [inline rust/lance/src/index/vector/builder.rs]: Maybe a better name?
```suggestion
enum PartitionAdjustment {
```

File: rust/lance/src/index/vector/builder.rs [hunk 6]
```diff
@@ -1979,6 +1944,12 @@ enum ReassignPartition {
...
+    Split(usize),
```
Comment (wjones127) [inline rust/lance/src/index/vector/builder.rs:1952]: It wasn't obvious at first glance if this mean "split into N" partition, or "split partition n". I think it's the second one.
```suggestion
    /// Split partition at given id
    Split(usize),
```
