### PR TITLE
fix: remove data files with all dropped columns

### LINKED ISSUE #2128: Dropped columns seen after adding new columns
```python
import lance
import pyarrow as pa

tab = pa.table({'x': [1, 2, 3]})

ds = lance.write_dataset(tab, 'test3')
ds.add_columns({'y': '2 * x'})
ds.to_table()
```

```
pyarrow.Table
x: int64
y: int64
----
x: [[1,2,3]]
y: [[2,4,6]]
```

```python
ds.drop_columns(['y'])
ds.add_columns({'z': '3 * x'})
ds.to_table()
```

```
pyarrow.Table
x: int64
z: int64
----
x: [[1,2,3]]
z: [[2,4,6]]
```

### PR DESCRIPTION
**Pull request by wjones127**
Fixes #2128

This also adds an automatic repair to schemas that have been corrupted by this bug. Users can call `dataset.validate()` to detect whether this issue affects them. If it does, they can call `dataset.delete("false")` and that will trigger an automatic repair on the dataset.

### CODE REVIEW

**Comment by wjones127** [comment]
I think I need to change how field ids are assigned in schemas.

Right now, methods like `Schema::merge()`, `Schema::extend()` and so on will assign all fields ids if they don't have one (that is, `id=-1`). It figures out which ids are free by finding the max id used in the schema and incrementing from there. This is a problem, because once we drop columns we can have ids that are "reserved" but not in the schema. For example, consider the following sequence of operations:

1. Create table: schema: `x (id=0)`
2. Add columns `y, z`: schema: `x (id=0), y (id=1), z (id=2)`
3. Drop column `z`: schema: `x (id=0), y (id=1)`

At this point, each fragment will have two data files: one with field `x`, and another with fields `y, z`. According to the schema, the max field id being used is 1. But according to the data files, the max id in use is 2. As long as we are keeping the fragment with y, we can't re-use field id 2. Therefore, using the max id *in the schema* isn't correct for assigning field ids.

Instead, we should keep track of which field ids are in-use by looking at the data files in the first fragment, like I do here:

https://github.com/lancedb/lance/blob/1f4767094944d41f3f1e845e36ec994c1b752efd/rust/lance-table/src/format/manifest.rs#L193-L199

What I propose is that:

1. `Schema::merge` and other methods on schema should *not* assign field ids anymore.
2. `Schema::set_field_ids()` should be called explicitly, and should take a max field id in use. This can be computed with the above function, based on the fields in the actual fragments.

**Review by albertlockett — APPROVED** [review]

**Comment by eddyxu** [comment]
Should we keep tracking these ids in the global schema/manifest? 
We may have partially materialized columns in some fragments but not others, if we'd like to support materialized views later.

**Comment by wjones127** [comment]
> Should we keep tracking these ids in the global schema/manifest? We may have partially materialized columns in some fragments but not others, if we'd like to support materialized views later.

Yeah I guess eventually reading from the first fragment won't be the best way to get the currently used fields. We can later add some global field on the manifest to track this, when this becomes relevant. Since I put the method to get the `max_field_id()` on the `Manifest`, I think these changes should provide an easy migration towards that.

File: rust/lance-core/src/datatypes/schema.rs [hunk 1]
```diff
@@ -421,8 +426,19 @@ impl Schema {
         Ok(())
     }
 
-    fn set_field_id(&mut self) {
-        let mut current_id = self.max_field_id().unwrap_or(-1) + 1;
+    /// Set the field IDs that are unspecified (that is, -1).
+    ///
```
Comment (westonpace) [inline rust/lance-core/src/datatypes/schema.rs:430]:
```suggestion
    /// Walk through the fields and assign a new field id to each field that does
    /// not have one (e.g. is set to -1)
    ///
```

File: rust/lance-table/src/format/manifest.rs [hunk 2]
```diff
@@ -184,6 +184,29 @@ impl Manifest {
...
+        let schema_max_id = self.schema.max_field_id();
+        let fragment_max_id = self.fragments.first().and_then(|f| {
+            f.files
+                .iter()
+                .flat_map(|file| file.fields.as_slice())
+                .max()
+                .cloned()
+        });
+        match (schema_max_id, fragment_max_id) {
+            (None, None) => None,
```
Comment (westonpace) [inline rust/lance-table/src/format/manifest.rs:201]: Is this case even possible?  Seems you could change the return type to `i32` if you just panic here.

File: rust/lance/src/io/commit.rs [hunk 3]
```diff
@@ -200,6 +201,73 @@ async fn migrate_manifest(
...
+        for ((file_pos, field_pos), new_field_id) in &file_field_mapping {
+            fragment.files[*file_pos].fields[*field_pos] = *new_field_id;
+        }
+    }
+
+    // Apply mapping to the schema
+    for (old_field_id, new_field_id) in &old_field_id_mapping {
+        let field = manifest.schema.mut_field_by_id(*old_field_id).unwrap();
+        field.id = *new_field_id;
+    }
```
Comment (westonpace) [inline rust/lance/src/io/commit.rs:250]: How does this part work.  If the data files had a duplicate id we have something like...

```
Fragment 0:
  Data File 0:
    Field 0
    Field 1
  Data File 1:
    Field 0
```

I understand the above loop (replace (file-1,field-0) with field id 2) but how can we fix the schema? Isn't the schema:

```
Schema:
  field 0
  field 1
  field 0
```

If we run through this loop aren't we replacing the first instance of `field 0` with `field 2`?  Wouldn't we want to replace the last instance of `field 0`?

File: rust/lance/src/io/commit.rs [hunk 4]
```diff
@@ -200,6 +201,73 @@ async fn migrate_manifest(
     Ok(())
 }
 
+/// Fix schema in case of duplicate field ids.
+///
+/// See test dataset v0.10.5/corrupt_schema
+fn fix_schema(manifest: &mut Manifest) -> Result<()> {
+    let mut field_id_seed = manifest.max_field_id().unwrap_or(-1) + 1;
```
Comment (westonpace) [inline rust/lance/src/io/commit.rs:208]: Is there any way we can detect things are valid and short-circuit all this computation (might be expensive if there are many columns)?

**Review by westonpace — APPROVED** [review]
A few questions but this looks like a good fix

File: rust/lance/src/io/commit.rs (hunk 3 above)
Comment (wjones127) [reply rust/lance/src/io/commit.rs:250]: The schema will never have duplicate ids, since we've been using the `max_field_id` from the schema thus far. The case is more like:

```
Schema:
  field 1
  field 0
```

Where `field 0` is loading the one from `Data File 0` when it should be loading from `Data File 1`. Therefore, we map it to `field 2` so that there's no conflict.

File: rust/lance/src/io/commit.rs (hunk 4 above)
Comment (wjones127) [reply rust/lance/src/io/commit.rs:208]: As written, if the dataset is fine, all it will do is collect all the field ids into a `HashSet`. The other data structures are only written to if we detect a duplicate field ids.

We could quickly short circuit if there is only 1 data file per fragment. That will avoid this computation for 90% of datasets out there, since most users aren't adding new columns.

File: rust/lance/src/io/commit.rs (hunk 3 above)
Comment (westonpace) [reply rust/lance/src/io/commit.rs:250]: Ah, I see, this only fixes schemas that have corrupted by the specific add/remove/add-back process.  So the field ids we are mapping from are field ids that shouldn't exist in the schema at all.
