### PR TITLE
fix: optimize index with no new data

### LINKED ISSUE #4016: Duplicate results from vector search after `optimize_indices` on table with up-to-date IVF_PQ index
Originally reported in https://github.com/lancedb/lancedb/issues/2439

```python
import lance
import pyarrow as pa
import pyarrow.compute as pc

companies = [f"company_{i}" for i in range(3)]
data = pa.table({
    "id": range(1000),
    "vector": pa.FixedSizeListArray.from_arrays(
        pc.random(16 * 1000).cast(pa.float32()),
        16
    ),
})
ds = lance.write_dataset(data, "memory://")
ds.create_index("vector", "IVF_PQ", num_partitions=2, num_sub_vectors=4)
vec = pc.random(16).cast(pa.float32())

# Before: no duplicates
ds.to_table(nearest=dict(column="vector", q=vec, k=5))

ds.optimize.optimize_indices()

# After: duplicates
ds.to_table(nearest=dict(column="vector", q=vec, k=5))
```

### PR DESCRIPTION
**Pull request by wjones127**
Fixes #4016

### CODE REVIEW

File: rust/lance/src/index/vector/builder.rs [hunk 1]
```diff
@@ -465,6 +465,10 @@ impl<S: IvfSubIndex + 'static, Q: Quantization + 'static> IvfIndexBuilder<S, Q>
         data: Option<impl RecordBatchStream + Unpin + 'static>,
     ) -> Result<&mut Self> {
         if data.is_none() {
+            // If we don't specify the shuffle reader, it's going to re-read the
+            // dataset and duplicate the data.
+            self.shuffle_reader = Some(todo!("empty reader"));
```
Comment (wjones127) [inline rust/lance/src/index/vector/builder.rs]: @BubbleCal could use your help here. What's the best way to do this?

**Review by BubbleCal — COMMENTED** [review]
Thanks for this work!

File: rust/lance/src/index/vector/builder.rs (hunk 1 above)
Comment (BubbleCal) [reply rust/lance/src/index/vector/builder.rs]: let's add an EmptyReader in:
rust/lance-index/src/vector/v3/shuffler.rs
then we can use it here, the impl should be simple
