### PR TITLE
fix: handle larger arrays in take

### LINKED ISSUE #1382: take can't handle vectors with more than u32::MAX values

### PR DESCRIPTION
**Pull request by wjones127**
Closes #1382

TODO: 
* [x] Test with a dataset that has 5 billion values

### CODE REVIEW

**Comment by wjones127** [comment]
I'm unable to reproduce, even on a machine with 64 GB of memory because it gets killed for OOM. :(

File: rust/lance/src/dataset.rs [hunk 1]
```diff
@@ -812,51 +815,84 @@ impl Dataset {
         Ok(counts.iter().sum())
     }
 
-    pub async fn take(&self, row_indices: &[usize], projection: &Schema) -> Result<RecordBatch> {
-        let mut sorted_indices: Vec<u32> =
-            Vec::from_iter(row_indices.iter().map(|indice| *indice as u32));
-        sorted_indices.sort();
+    pub async fn take(&self, row_indices: &[u64], projection: &Schema) -> Result<RecordBatch> {
+        let mut sorted_indices: Vec<usize> = (0..row_indices.len()).collect();
```
Comment (westonpace) [inline rust/lance/src/dataset.rs:819]: Minor but do you want to return early if `row_indices` is empty?  Mainly this would allow `take` with zero indices to work even on an empty dataset.  Though I'm sure that's a corner case.

File: rust/lance/src/dataset.rs [hunk 2]
```diff
@@ -812,51 +815,84 @@ impl Dataset {
...
+        })?;
+        let mut current_fragment_len = current_fragment.count_rows().await?;
+        let mut curr_fragment_offset: u64 = 0;
+        let mut current_fragment_end = current_fragment_len as u64;
+        let mut start = 0;
+        let mut end = 0;
+
+        for index in sorted_indices {
+            // Get the index
+            let row_index = row_indices[index];
```
Comment (westonpace) [inline rust/lance/src/dataset.rs:843]: Maybe `row_address` or `row_id`?

**Review by westonpace — APPROVED** [review]

File: rust/lance/src/dataset.rs (hunk 2 above)
Comment (wjones127) [reply rust/lance/src/dataset.rs:843]: These aren't `row_id`. They are more like `row_number`, in that there is no gap between fragments.

File: rust/lance/src/dataset.rs (hunk 1 above)
Comment (wjones127) [reply rust/lance/src/dataset.rs:819]: Not a bad idea 👍
