### PR TITLE
fix: cleanup external staging manifests

### LINKED ISSUE #1201: add logic to clean up stray staged manifests
In #1190 we added `ExternalManifestStore`, where we first write a manifest with a random path. This manifest with a random path could become orphaned and needs to be cleaned up.

### LINKED ISSUE #2059: Temp manifest files are not cleaned up after commit using external manifest store
When using external manifest store, step 3 of commit does this copy:
`COPY_OBJECT_STORE mydataset.lance/_versions/{version}.manifest-{uuid} mydataset.lance/_versions/{version}.manifest`

https://lancedb.github.io/lance/format.html#external-manifest-store

This leaves the file `mydataset.lance/_versions/{version}.manifest-{uuid}` which is unused and never cleaned up. We should remove this file as part of the commit procedure.

Also, when we run dataset `cleanup`, these temporary files should be removed form object store.

### PR DESCRIPTION
**Pull request by wjones127**
* Fixes #2059
* Fixes #1201

### CODE REVIEW

File: rust/lance-table/src/io/commit/external_manifest.rs [hunk 1]
```diff
@@ -76,6 +76,50 @@ pub struct ExternalManifestCommitHandler {
...
+        {
+            Ok(_) => {}
+            Err(ObjectStoreError::NotFound { .. }) => return Ok(final_manifest_path), // Another writer beat us to it.
+            Err(e) => return Err(e.into()),
+        };
+
+        // step 2: flip the external store to point to the final location
+        self.external_manifest_store
+            .put_if_exists(base_path.as_ref(), version, final_manifest_path.as_ref())
+            .await?;
```
Comment (westonpace) [inline rust/lance-table/src/io/commit/external_manifest.rs:110]: It looks like you have `store.copy` and then `external_manifest_store.put_if_exists`.

However, in the original code blocks it looks like it was `store.copy` and then `store.rename` and then `external_manifest_store.put_if_exists`.  What happened to the `rename`?

**Review by westonpace — APPROVED** [review]
The cleanup looks nice, I just want to make sure dropping the `rename` was intentional.

File: rust/lance-table/src/io/commit/external_manifest.rs (hunk 1 above)
Comment (wjones127) [reply rust/lance-table/src/io/commit/external_manifest.rs:110]: I'm assuming that I could do this given the TODO:

```
// TODO: remove copy-rename once we upgrade object_store crate
```

This is likely from:

 * https://github.com/apache/arrow-rs/issues/4758
 * https://github.com/apache/arrow-rs/issues/5503
