### PR TITLE
fix: convert some panics into errors

### LINKED ISSUE #5257: Panic on errors in `shuffle_data`
Found in LanceDB CI:

```
8cdf2ec69b3663b6/9f368fa/rust/lance/src/index/vector/builder.rs:658:29:
do this better: error reading first batch: Index { message: "PQ: num_sub_vectors must be divisible by 2 for num_bits=4, but got 1", location: Location { file: "/root/.cargo/git/checkouts/lance-8cdf2ec69b3663b6/9f368fa/rust/lance-index/src/vector/pq.rs", line: 138, column: 27 } }
```

We seem to panic instead of return an error in some cases in `shuffle_data`:

https://github.com/lancedb/lance/blob/27d8ac56cd875595d98dce73d4f42b4a964136fe/rust/lance/src/index/vector/builder.rs#L658

### PR DESCRIPTION
**Pull request by wjones127**
Closes #5257

### CODE REVIEW

File: rust/lance/src/index/vector/builder.rs [hunk 1]
```diff
@@ -652,10 +652,10 @@ impl<S: IvfSubIndex + 'static, Q: Quantization + 'static> IvfIndexBuilder<S, Q>
             .peekable(),
         );
 
-        let batch = transformed_stream.as_mut().peek().await;
+        let batch = transformed_stream.as_mut().peek_mut().await;
         let schema = match batch {
             Some(Ok(b)) => b.schema(),
-            Some(Err(e)) => panic!("do this better: error reading first batch: {:?}", e),
+            Some(Err(e)) => return Err(std::mem::replace(e, Error::Stop)),
```
Comment (westonpace) [inline rust/lance/src/index/vector/builder.rs:658]: Does this swallow the underlying error?

**Review by westonpace — APPROVED** [review]
Approve assuming we aren't deleting potentially useful info (maybe we can log it?)

File: rust/lance/src/index/vector/builder.rs (hunk 1 above)
Comment (wjones127) [reply rust/lance/src/index/vector/builder.rs:658]: No it returns the underlying error. Since we are peeking into the stream, we only have an `&mut Error` not an owned `Error`. So we just use `std::mem::replace` to get the owned `Error` and replace the one in the stream with a dummy `Error::Stop`.
