### PR TITLE
fix: filter out null values when sampling for index training

### LINKED ISSUE #3400: Failure to create index after upserting with subschema
Details TBD

It appears the underlying error is actually: https://github.com/lancedb/lance/issues/3402

### LINKED ISSUE #3402: Creating IVF_PQ index on vector column with nulls fails if distance_type = "dot"
```python
import pyarrow as pa
import pyarrow.compute as pc
import lance

nrows = 10_000
dims = 16
values = pc.random(nrows * dims).cast(pa.float32())
vectors = pa.FixedSizeListArray.from_arrays(values, dims)
set_null = pc.less(pc.random(nrows), 0.7) # 70% nulls
vectors = pc.if_else(set_null, pa.scalar(None), vectors)
table = pa.table({"vectors": vectors})

ds = lance.write_dataset(table, "memory://")
# Succeeds:
ds.create_index("vectors", "IVF_PQ", metric="l2", num_partitions=2, num_sub_vectors=2)

# Fails:
ds.create_index("vectors", "IVF_PQ", metric="dot", num_partitions=2, num_sub_vectors=2, replace=True)
```

```
thread '<unnamed>' panicked at /Users/runner/work/lance/lance/rust/lance-index/src/vector/pq.rs:373:9:
assertion `left == right` failed
  left: 7045
 right: 0
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: <lance_index::vector::pq::ProductQuantizer as lance_index::vector::quantizer::Quantization>::build
   5: lance::index::vector::ivf::build_ivf_pq_index::{{closure}}
   6: lance::index::vector::build_vector_index::{{closure}}::{{closure}}
   7: lance::index::<impl lance_index::traits::DatasetIndexExt for lance::dataset::Dataset>::create_index::{{closure}}::{{closure}}
   8: lance::index::<impl lance_index::traits::DatasetIndexExt for lance::dataset::Dataset>::create_index::{{closure}}
   9: lance::executor::BackgroundExecutor::result_or_interrupt::{{closure}}
  10: lance::executor::BackgroundExecutor::block_on
  11: lance::dataset::Dataset::create_index
  12: lance::dataset::Dataset::__pymethod_create_index__
  13: pyo3::impl_::trampoline::trampoline
  14: lance::dataset::<impl pyo3::impl_::pyclass::PyMethods<lance::dataset::Dataset> for pyo3::impl_::pyclass::PyClassImplCollector<lance::dataset::Dataset>>::py_methods::ITEMS::trampoline
  15: __PyEval_EvalFrameDefault
  16: _PyEval_EvalCode
  17: _run_mod
  18: _PyRun_InteractiveOneObjectEx
  19: __PyRun_InteractiveLoopObject
  20: __PyRun_AnyFileObject
  21: _PyRun_AnyFileExFlags
  22: _Py_RunMain
  23: _pymain_main
  24: _main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/willjones/mambaforge/envs/lancedb-dev/lib/python3.11/site-packages/lance/dataset.py", line 2207, in create_index
    self._ds.create_index(
pyo3_runtime.PanicException: assertion `left == right` failed
  left: 7045
 right: 0
```

### PR DESCRIPTION
**Pull request by wjones127**
We were not filtering out null values when sampling. Because we often call `array.values()` on Arrow arrays, which ignores the null bitmap, we are often silently treating the nulls as zeros (or possibly undefined values). Only thing that caught these nulls is an assertion. However, residualization occurring with L2 and Cosine often meant that these values were transformed and null information was lost before the assertion, which is why it got past previous unit tests.

This PR adds more assertions validating there aren't nulls, and makes sure the sampling code handles null vectors.

Closes #3402
Closes #3400

### CODE REVIEW

File: rust/lance/src/index/vector/ivf.rs [hunk 1]
```diff
@@ -2215,6 +2222,77 @@ mod tests {
...
+                MetricType::L2,
+                IvfBuildParams::new(2),
+                PQBuildParams::new(2, 4),
+            ),
+            VectorIndexParams::with_ivf_pq_params(
+                MetricType::Dot,
+                IvfBuildParams::new(2),
+                PQBuildParams::new(2, 4),
+            ),
+            VectorIndexParams::with_ivf_pq_params(
```
Comment (BubbleCal) [inline rust/lance/src/index/vector/ivf.rs:2241]: this looks same as the previous one, do you want to try `cosine` to 8bit PQ?

File: rust/lance/src/index/vector/ivf.rs [hunk 2]
```diff
@@ -2215,6 +2222,77 @@ mod tests {
             .await;
     }
 
+    #[rstest]
+    #[tokio::test]
+    async fn test_create_index_nulls(
```
Comment (BubbleCal) [inline rust/lance/src/index/vector/ivf.rs:2227]: i'm thinking should we add some tests for verifying recall? then we can know whether flat search handles nulls well.

it might be good to modify this test https://github.com/lancedb/lance/blob/main/rust/lance/src/index/vector/ivf/v2.rs to contain half rows with nulls

Comment (wjones127) [reply rust/lance/src/index/vector/ivf.rs:2227]: I was thinking, is there a way to count rows that are present in the index? I assume if it’s null then we don’t write it to the index file, right?

File: rust/lance/src/index/vector/ivf.rs (hunk 1 above)
Comment (wjones127) [reply rust/lance/src/index/vector/ivf.rs:2241]: Ah I think it was a duplicate. I was going to create one variant for V3, but ended up doing that a different way. Will remove it.

File: rust/lance/src/index/vector/ivf.rs (hunk 2 above)
Comment (wjones127) [reply rust/lance/src/index/vector/ivf.rs:2227]: I have updated the test so it asserts we can use search to get all the non-null vectors back. But I am not getting the results I expect. I could use your advice to know what the expected behavior of these indices should be when there are lots of null vectors.

Comment (BubbleCal) [reply rust/lance/src/index/vector/ivf.rs:2227]: it seems no such way to count that now, it could be easy for v3 index by counting the num rows of storage file.

**Review by BubbleCal — APPROVED** [review]

File: rust/lance/src/index/vector/ivf.rs (hunk 2 above)
Comment (wjones127) [reply rust/lance/src/index/vector/ivf.rs:2227]: > I could use your advice to know what the expected behavior of these indices should be when there are lots of null vectors.

@BubbleCal Could you help me make sense of the output of this test? https://github.com/lancedb/lance/actions/runs/12918160780/job/36026117407?pr=3404

I was expecting search to only return non-null rows, but it seems like we are getting some null vectors in the results.

File: rust/lance/src/index/vector/utils.rs [hunk 3]
```diff
@@ -107,17 +107,72 @@ pub async fn maybe_sample_training_data(
...
+    } else if num_rows > sample_size_hint && is_nullable {
+        // Need to filter out null values
+        // Use a scan to collect row ids. Then sample from the row ids. Then do take.
+        let row_addrs = dataset
+            .scan()
+            .filter_expr(datafusion_expr::col(column).is_not_null())
+            .with_row_address()
+            .project::<&str>(&[])?
+            .try_into_batch()
+            .await?;
```
Comment (wjones127) [inline rust/lance/src/index/vector/utils.rs:140]: @westonpace How expensive do you think this query is? This is filtering for non-null vectors and getting the row ids. Do you think there are easy optimizations we could do? If so, I'd like to capture that in a ticket.

File: rust/lance/src/index/vector/utils.rs [hunk 4]
```diff
@@ -107,17 +107,72 @@ pub async fn maybe_sample_training_data(
...
+
+    let batch = if num_rows > sample_size_hint && !is_nullable {
         let projection = dataset.schema().project(&[column])?;
         let batch = dataset.sample(sample_size_hint, &projection).await?;
         info!(
             "Sample training data: retrieved {} rows by sampling",
             batch.num_rows()
         );
         batch
+    } else if num_rows > sample_size_hint && is_nullable {
```
Comment (westonpace) [inline rust/lance/src/index/vector/utils.rs:131]: Hmm...shouldn't you be using `sample_size_hint`?  In this branch there are way more rows than we need.  E.g. to train a dataset with 1B rows we need 30K partitions and so `sample_size_hint` will be ~8M.  It looks like you're going to read all 1B vectors.  Also, I don't see any randomization.

Did you mean to shuffle `row_addrs`?

FWIW, in the python, we do this (https://github.com/lancedb/lance/blob/58c5e27ff1534ae82041eeb73c55a555da2bcd65/python/python/lance/sampler.py#L137):

* Create a randomized take stream that will eventually take the entire dataset
* Pull from the take stream and filter out nulls in-memory until we have `sample_size_hint` rows.
* Stop pulling from the take stream

To speed up the "randomized take stream" we actually stream random "contiguous shards" that are sized to give us at least 2K take operations if there are no nulls (IIRC)

**Review by westonpace — COMMENTED** [review]
I'm probably just missing something but I don't see where we are sampling.

File: rust/lance/src/index/vector/utils.rs [hunk 5]
```diff
@@ -107,17 +107,72 @@ pub async fn maybe_sample_training_data(
...
+        // Need to filter out null values
+        // Use a scan to collect row ids. Then sample from the row ids. Then do take.
+        let row_addrs = dataset
+            .scan()
+            .filter_expr(datafusion_expr::col(column).is_not_null())
```
[the remark this answers is not in the document]
Comment (wjones127) [reply rust/lance/src/index/vector/utils.rs:136]: Sorry, forgot the sampling bit. It sounds like the best thing for now is `scan->filter` + reservoir sampling?

**Review by westonpace — APPROVED** [review]
Thanks, `random_ranges` looks useful.  Maybe we can simplify the python impls at some point in the future.
