### PR TITLE
fix: make PageTable handle multiple files

### LINKED ISSUE #1331: Read after merge attempts to read past end of data file
Originally reported on Discord: https://discord.com/channels/1030247538198061086/1105226910528716912/1155949275721768960

After using `merge()` we can read the dataset back. However, after re-instantiating the dataset, we get the error:

```
InvalidInputException: Invalid Input Error: arrow_scan: get_next failed(): Invalid: C Data interface error: Io error: Execution error: External error: Execution error: LanceError(IO): failed to read all bytes from file: expected 480, got 437, /home/runner/work/lance/lance/rust/lance/src/io/local.rs:121:31
```

The root cause is we are passing an incorrect number of columns to `PageTable::load`. We are passing the total number of columns in the fragment, and not the total in the file. Thus, it reads past the end of the file.

This doesn't happen before re-instantiating the dataset because the page tables are already cached with the correct number of columns.

<details><summary>Reproducible example</summary>
<p>

```python
import lance
import duckdb

pop_interactive_pdfs = duckdb.sql("""
SELECT  i, 
        md5(CAST(i AS VARCHAR)) AS text 
FROM range(10000) tbl(i)
""")

lance_ds = lance.write_dataset(
    pop_interactive_pdfs.fetch_arrow_reader(),
    ".data/reproduce_bug_3.lance",
    mode="overwrite",
)

embedding_df = duckdb.sql("""
SELECT  i, 
        md5(CAST(i AS VARCHAR)) AS vec
FROM range(10000) tbl(i)
""")
lance_ds.merge(embedding_df.fetch_arrow_reader(), "i")

# There is no problem if I query here
duckdb.sql("SELECT * FROM lance_ds")

# If we reload the dataset, we get an error
lance_ds = lance.dataset(".data/reproduce_bug_3.lance")
duckdb.sql("SELECT * FROM lance_ds")
```

</p>
</details>

### PR DESCRIPTION
**Pull request by wjones127**
Currently, `PageTable` assumes there are fields `0..num_columns`, where `num_columns` is the total number of columns in the dataset. This works for new files added, because we always write `0..(max_field_id + 1)` entries in the page table, but it breaks for old data files who have fewer fields. This is why after merge we can read the new columns (in the new files), but not the old columns. Also, because the PageTable is cached, we could read while using the same instance of `LanceDataset`, but as soon as we loaded in a new session, the PageTables would be re-read and break.

This PR modifies the `PageTable` format slightly so that the fields start at the minimum field id in that file's schema. This is backwards compatible for all tables that only have one data file per fragment, but breaks tables that have more than one file. However, seeing as the latter case is broken already, I think this breaking change is fine.

Closes #1331.

### CODE REVIEW

File: rust/lance/src/io/local.rs [hunk 1]
```diff
@@ -110,20 +110,8 @@ impl ObjectReader for LocalObjectReader {
...
-                return Err(Error::IO {
-                    message: format!(
-                        "failed to read all bytes from file: expected {}, got {}",
-                        range.len(),
-                        bytes_read
-                    ),
-                    location: location!(),
-                });
-            }
+            file.read_exact_at(buf.as_mut(), range.start as u64)?;
```
Comment (wjones127) [inline rust/lance/src/io/local.rs:113]: This isn't the cause of the bug, but I did realize we are gambling a bit by using `read_at`. From the [`read_at` docs](https://doc.rust-lang.org/std/os/unix/fs/trait.FileExt.html#tymethod.read_at):

> Note that similar to [File::read](https://doc.rust-lang.org/std/fs/struct.File.html#method.read), it is not an error to return with a short read.

Instead of just erroring when the OS doesn't fill the buffer, we can just use a method that will handle this for us.

**Review by eddyxu — APPROVED** [review]
It looks fine to me.

File: rust/lance/src/io/local.rs [hunk 2]
```diff
@@ -111,21 +111,36 @@ impl ObjectReader for LocalObjectReader {
...
+                offset += n as u64;
+            }
+            Err(ref e) if e.kind() == std::io::ErrorKind::Interrupted => {}
+            Err(e) => return Err(e),
+        }
+    }
+    if !buf.is_empty() {
+        Err(std::io::Error::new(
+            std::io::ErrorKind::UnexpectedEof,
+            "failed to fill whole buffer",
```
Comment (westonpace) [inline rust/lance/src/io/local.rs:141]: Minor nit: might be nice to say "expected N bytes but only received Y"

File: rust/lance/src/dataset.rs [hunk 3]
```diff
@@ -2383,6 +2383,20 @@ mod tests {
         .unwrap();
 
         assert_eq!(actual, expected);
+
+        // Validate we can still read after re-instantiating dataset, which
+        // clears the cache.
+        let dataset = Dataset::open(test_uri).await.unwrap();
```
Comment (eddyxu) [inline rust/lance/src/dataset.rs:2389]: Is this where the bug was reproduced?

**Review by westonpace — COMMENTED** [review]
Is it possible to delete columns from a dataset?  Will that still be handled?

File: rust/lance/src/dataset.rs (hunk 3 above)
Comment (wjones127) [reply rust/lance/src/dataset.rs:2389]: Yes, once we reloaded the table, the in-memory version of the PageTable was gone and we are reading from disk, which is where the problems start.

**Comment by wjones127** [comment]
> Is it possible to delete columns from a dataset? Will that still be handled?

I don't think we expose this yet, but we plan to allow that.

We should define the semantics better in a future PR. Basically, similar to how there is a distinction of "physical rows" and "logical rows" (that is, after deletions are applied), we should consider the `schema` of the dataset the logical schema, while the list of field ids in fragments should be considered physical and includes removed columns.

File: rust/lance/src/io/local.rs (hunk 2 above)
Comment (wjones127) [reply rust/lance/src/io/local.rs:141]: Sure.
