### PR TITLE
fix: add versioning and bypass broken row counts

### LINKED ISSUE #1531: Incorrect physical_rows recorded when migrating from old versions of tables with deletions
v0.8.0: We started recording the number of physical rows, but implementation used `count_rows()` to compute this.
v0.7.5 is the version right before that.

## How to reproduce

Install pylance 0.7.5
```shell
python -m venv .venv
source .venv/bin/activate
pip install pylance==0.7.5
python
```

Write a table, and delete some rows
```python
import lance
import pyarrow as pa

tab = pa.table({'x': range(100)})
dataset = lance.write_dataset(tab, 'test')
dataset.delete("x >= 10 and x < 20")
dataset.count_rows()
```

```
90
```

Now, install pylance 0.8.0:
```shell
pip install pylance==0.8.0
python
```

Count rows at first is correct. However, once we write to the table, it becomes incorrect:
```python
import lance
import pyarrow as pa

dataset = lance.dataset('test')
dataset.count_rows() # 90

tab = pa.table({'x': range(5)})
dataset = lance.write_dataset(tab, 'test', mode='append')
dataset.count_rows() # 85 
dataset.to_table().num_rows # 95
```

### LINKED ISSUE #1535: Create a test framework to validate compatibility between Lance versions
We currently only test with a single Lance version, but there can be incompatibilities between versions that we need to test for. Right now we can only do so manually.

We can start checking in tables from different versions of Lance that are important. These can be copied and uses as the basis for testing migrations and backwards compatibility. For example, pylance 0.7.5 is the last version before we started tracking `physical_rows` on fragments, so we'll want a table from that version so we can check we can successfully migrate from there.

### PR DESCRIPTION
**Pull request by wjones127**
Adds a new feature: `WriterVersion` in the manifest.

Also fixes two bugs:
* #1531 Adds bypass logic to read correct `physical_rows` when old version is detected.
  Will update the value on write as needed.
* When `migrate_fragments` runs, we do it on the new fragments and not the old,
  fixing a data loss issue.

Fixes #1531
Fixes #1535

### CODE REVIEW

File: rust/lance/src/io/commit.rs [hunk 1]
```diff
@@ -154,20 +154,27 @@ pub(crate) async fn commit_new_dataset(
...
+                        .unwrap_or_default()
+                        > 0)
+        })
+    {
         return Ok(());
     }
 
-    manifest.fragments = Arc::new(migrate_fragments(dataset, dataset.fragments()).await?);
+    manifest.fragments =
+        Arc::new(migrate_fragments(dataset, &manifest.fragments, recompute_stats).await?);
```
Comment (wjones127) [inline rust/lance/src/io/commit.rs:177]: I found another critical bug here 😞 

We migrate the old fragments not the new, so this basically is rolling back the transactions changes. This means data loss in most cases.

**Comment by wjones127** [comment]
Validated this manually building off of repro in README:

## Repro setup

Install pylance 0.7.5
```shell
python -m venv .venv
source .venv/bin/activate
pip install pylance==0.7.5
python
```

Write a table, and delete some rows
```python
import lance
import pyarrow as pa

tab = pa.table({'x': range(100)})
dataset = lance.write_dataset(tab, 'test')
dataset.delete("x >= 10 and x < 20")
dataset.count_rows()
```

```
90
```

Now, install pylance 0.8.0:
```shell
pip install pylance==0.8.0
python
```

Count rows at first is correct. However, once we write to the table, it becomes incorrect:
```python
import lance
import pyarrow as pa

dataset = lance.dataset('test')
dataset.count_rows() # 90

tab = pa.table({'x': range(10)})
dataset = lance.write_dataset(tab, 'test', mode='append')
dataset.count_rows() # 90 
dataset.to_table().num_rows # 100
```

## Steps in this fix

Using feature branch:

```python
import lance
dataset = lance.dataset("test")

dataset.count_rows()
```
```
100
```

```python
import pyarrow as pa
tab = pa.table({'x': range(2)})
dataset = lance.write_dataset(tab, dataset.uri, mode="append")
dataset.count_rows()
```

```
102
```

## Validating in old version

Back in pylance 0.8.0:

```python
>>> import lance
>>> dataset = lance.dataset('test')
>>> dataset.count_rows()
```
```
102
```

File: python/python/lance/fragment.py [hunk 2]
```diff
@@ -347,7 +347,7 @@ def delete(self, predicate: str) -> FragmentMetadata | None:
         >>> dataset = lance.write_dataset(tab, "dataset")
         >>> frag = dataset.get_fragment(0)
         >>> frag.delete("a > 1")
-        Fragment { id: 0, files: ..., deletion_file: Some(...), physical_rows: 3 }
+        Fragment { id: 0, files: ..., deletion_file: Some(...), physical_rows: Some(3) }
```
Comment (eddyxu) [inline python/python/lance/fragment.py:350]: in what condition that `physical_rows = None`?

File: rust/lance/src/io/commit.rs (hunk 1 above)
Comment (eddyxu) [reply rust/lance/src/io/commit.rs:176]: Could we have some tests to cover this case?

File: python/python/lance/fragment.py (hunk 2 above)
Comment (wjones127) [reply python/python/lance/fragment.py:350]: When the dataset was written prior to 0.8.0, this field is not filled in (because the field didn't exist then).

Comment (wjones127) [reply python/python/lance/fragment.py:350]: BTW that change is more relevant to #1529, which this PR is based on. So worth reviewing that one first.

File: rust/lance/src/io/commit.rs (hunk 1 above)
Comment (wjones127) [reply rust/lance/src/io/commit.rs:176]: Working on adding tests now.

Comment (wjones127) [reply rust/lance/src/io/commit.rs:176]: Tests have been added.

Comment (wjones127) [reply rust/lance/src/io/commit.rs:176]: I'm confused right now. This seems like it would have caused new fragments to be ignored, but my repro in https://github.com/lancedb/lance/issues/1531 does not seem to cause this.

Comment (wjones127) [reply rust/lance/src/io/commit.rs:176]: Figured it out, the data loss bug was added in a later version.

**Review by chebbyChefNEQ — APPROVED** [review]
