### PR TITLE
fix: knn search works after compaction

### LINKED ISSUE #1303: KNN query after compaction may fail
We can get errors like:

```
pyarrow.lib.ArrowInvalid: C Data interface error: Io error: Execution error: External error: Execution error: ExecNode(Projection): thread panicked: task 357 panicked
```

```
thread 'lance_background_thread' panicked at 'assertion failed: `(left == right)`
  left: `6`,
 right: `10`', /Users/willjones/Documents/lance/rust/lance/src/dataset.rs:885:9
```

### PR DESCRIPTION
**Pull request by wjones127**
Fixes #1303 

After compaction, the fragment ids may not be in sequential order. We were using 
`binary_search` to re-order results received from parallel `Fragment::take_rows()` calls, 
which requires sorted data. This PR switches to just doing linear search for now, which 
doesn't require sorting.

We should optimize this code path better in the future, but the batches are small enough for 
linear search is likely not too slow.

### CODE REVIEW

File: rust/lance/src/dataset/transaction.rs
Comment (wjones127) [inline rust/lance/src/dataset/transaction.rs:1]: These changes aren't actually related to the fix; I was speculating something might be wrong here when first looking. However, I'm keeping them since they improve test coverage, which is always nice :)

File: python/python/tests/test_dataset.py [hunk 1]
```diff
@@ -802,7 +814,15 @@ def test_dataset_optimize(tmp_path: Path):
...
-    assert dataset.version == 2
+    assert dataset.version == 4
+
+    fragment_ids = [f.fragment_id for f in dataset.get_fragments()]
+    # Note that fragment_ids are out of order. Fragments 1 - 10 are replaced
+    # by a new compacted fragment, fragment 12.
+    assert fragment_ids == [0, 12, 11]
+
+    # Make sure we can query successfully.
+    dataset.to_table(nearest=dict(column="vector", q=[0] * ndim))
```
Comment (wjones127) [inline python/python/tests/test_dataset.py:825]: I have verified locally that this fails without the fix in `dataset.rs`.

File: rust/lance/src/dataset.rs [hunk 2]
```diff
@@ -878,9 +878,16 @@ impl Dataset {
...
-            .filter_map(|o| returned_row_ids.binary_search(o).ok().map(|pos| pos as u64))
+            .filter_map(|o| {
+                returned_row_ids
+                    .iter()
+                    .position(|id| id == o)
+                    .map(|pos| pos as u64)
+            })
             .collect();
 
+        debug_assert_eq!(remapping_index.len(), one_batch.num_rows());
```
Comment (chebbyChefNEQ) [inline rust/lance/src/dataset.rs:889]: should we remove this?

**Review by chebbyChefNEQ — APPROVED** [review]

**Comment by chebbyChefNEQ** [comment]
nit: let's add a issue to track compacting in order?

File: rust/lance/src/dataset.rs (hunk 2 above)
Comment (wjones127) [reply rust/lance/src/dataset.rs:889]: I'd like to keep it. It's a reminder of the invariant we need to keep in the function, and is ignored in release builds.

**Comment by wjones127** [comment]
> nit: let's add a issue to track compacting in order?

It's actually a feature, not a bug. Compaction preserves insertion order. But that means fragment ids might be out of order, since we replace earlier ranges.

**Comment by chebbyChefNEQ** [comment]
> It's actually a feature, not a bug. Compaction preserves insertion order. But that means fragment ids might be out of order, since we replace earlier ranges.

I see. I guess we could cache a tree set or a map in the future
