### PR TITLE
fix: add graceful shutdown and start for rest namespace adapter

### LINKED ISSUE #5293: flaky test: TestTableOperations.test_drop_table
This test seems unstable:

```shell

_____________________ TestTableOperations.test_drop_table ______________________

self = <test_namespace_rest.TestTableOperations object at 0xff56ae5655b0>
rest_namespace = RestNamespace(RestNamespace { endpoint: "http://127.0.0.1:5798/", delimiter: "$" })

    def test_drop_table(self, rest_namespace):
        """Test dropping a table."""
        # Create parent namespace
        create_ns_req = CreateNamespaceRequest(id=["workspace"])
>       rest_namespace.create_namespace(create_ns_req)

python/tests/test_namespace_rest.py:260: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = RestNamespace(RestNamespace { endpoint: "http://127.0.0.1:5798/", delimiter: "$" })
request = CreateNamespaceRequest(id=['workspace'], mode=None, properties=None)

    def create_namespace(
        self, request: CreateNamespaceRequest
    ) -> CreateNamespaceResponse:
>       response_dict = self._inner.create_namespace(request.model_dump())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E       RuntimeError: Namespace error: Response error: ResponseContent { status: 500, content: "{\"error\":{\"message\":\"Failed to get latest version: Not found: tmp/tmpuaghetk4/__manifest/_versions, /home/runner/work/lance/lance/rust/lance-table/src/io/commit.rs:355:23\",\"type\":\"InternalServerError\"}}", entity: Some(UnknownValue(Object {"error": Object {"message": String("Failed to get latest version: Not found: tmp/tmpuaghetk4/__manifest/_versions, /home/runner/work/lance/lance/rust/lance-table/src/io/commit.rs:355:23"), "type": String("InternalServerError")}})) }, /home/runner/work/lance/lance/rust/lance-namespace-impls/src/rest.rs:279:23

/opt/hostedtoolcache/Python/3.13.9/arm64/lib/python3.13/site-packages/lance/namespace.py:246: RuntimeError
```

More details could be found at https://github.com/lance-format/lance/actions/runs/19513077571/job/55857663028

### PR DESCRIPTION
**Pull request by jackye1995**
Closes #5293 

The test was flaky because the server in the last test is not properly shut down, and the one in new test fails to start and then client talks to the server in the last test.

Made the RestAdapter run non-blocking start instead of blocking serve, so that the python and java level can more gracefully handle start and shutdown.

### CODE REVIEW

**Comment by jackye1995** [comment]
Added some logging and found the issue:

```
[2025-12-01T20:07:29Z INFO  lance::namespace] PyRestAdapter::new() creating backend with impl=dir, host=127.0.0.1, port=13055
[2025-12-01T20:07:29Z INFO  lance::namespace] PyRestAdapter::new() properties={"root": "/tmp/tmpwvbvbg_7"}
[2025-12-01T20:07:29Z INFO  lance::namespace] PyRestAdapter::new() calling builder.connect()
[2025-12-01T20:07:29Z INFO  lance_namespace_impls::dir::manifest] create_or_get_manifest: attempting to load manifest from /tmp/tmpwvbvbg_7/__manifest
[2025-12-01T20:07:29Z DEBUG lance::events] target="lance::dataset_events" event="loading" uri="/tmp/tmpwvbvbg_7/__manifest" target_ref=None status="error" 
[2025-12-01T20:07:29Z INFO  lance_namespace_impls::dir::manifest] create_or_get_manifest: load result for /tmp/tmpwvbvbg_7/__manifest is Err
[2025-12-01T20:07:29Z INFO  lance_namespace_impls::dir::manifest] Creating new manifest table at /tmp/tmpwvbvbg_7/__manifest
[2025-12-01T20:07:29Z DEBUG lance::events] target="lance::dataset_events" event="loading" uri="/tmp/tmpwvbvbg_7/__manifest" target_ref=None status="error" 
[2025-12-01T20:07:29Z DEBUG lance::events] target="lance::dataset_events" event="writing" uri="/tmp/tmpwvbvbg_7/__manifest" mode=Create 
[2025-12-01T20:07:29Z DEBUG lance::events] target="lance::dataset_events" event="loading" uri="/tmp/tmpwvbvbg_7/__manifest" target_ref=None status="error" 
[2025-12-01T20:07:29Z DEBUG lance::events] target="lance::file_audit" mode="create" type="manifest" path="dummy" 
[2025-12-01T20:07:29Z DEBUG lance::events] target="lance::dataset_events" event="committed" uri="/tmp/tmpwvbvbg_7/__manifest" read_version=0 committed_version=1 detached=false operation="Overwrite" 
[2025-12-01T20:07:29Z INFO  lance_namespace_impls::dir::manifest] Successfully created manifest table at /tmp/tmpwvbvbg_7/__manifest, version=1, uri=/tmp/tmpwvbvbg_7/__manifest
[2025-12-01T20:07:29Z INFO  lance::namespace] PyRestAdapter::new() backend created successfully
[2025-12-01T20:07:29Z INFO  lance::namespace] PyRestAdapter::serve() starting server on 127.0.0.1:13055
[2025-12-01T20:07:29Z INFO  lance::namespace] PyRestAdapter::serve() sleeping 500ms to wait for server startup
[2025-12-01T20:07:29Z INFO  lance::namespace] PyRestAdapter::serve() background task started, calling adapter.serve()
[2025-12-01T20:07:29Z INFO  lance_namespace_impls::rest_adapter] RestAdapter::serve() binding to 127.0.0.1:13055
[2025-12-01T20:07:29Z INFO  lance::namespace] PyRestAdapter::serve() adapter.serve() returned: false
[2025-12-01T20:07:29Z INFO  lance::namespace] PyRestAdapter::serve() done sleeping, returning
[2025-12-01T20:07:29Z DEBUG reqwest::connect] starting new connection: http://127.0.0.1:13055/
[2025-12-01T20:07:29Z INFO  lance_namespace_impls::rest_adapter] REST create_namespace: received request for id=Some(["workspace"])
[2025-12-01T20:07:29Z DEBUG lance_namespace_impls::dir::manifest] DatasetConsistencyWrapper::reload() starting for uri=/tmp/tmp1ef2t_g9/__manifest, current_version=6
[2025-12-01T20:07:29Z ERROR lance_namespace_impls::dir::manifest] DatasetConsistencyWrapper::reload() failed to get latest version for uri=/tmp/tmp1ef2t_g9/__manifest, current_version=6, error=Not found: tmp/tmp1ef2t_g9/__manifest/_versions, /runner/_work/lance/lance/rust/lance-table/src/io/commit.rs:355:23
[2025-12-01T20:07:29Z ERROR lance_namespace_impls::rest_adapter] REST create_namespace: error=IO { source: Custom { kind: Other, error: "Failed to get latest version: Not found: tmp/tmp1ef2t_g9/__manifest/_versions, /runner/_work/lance/lance/rust/lance-table/src/io/commit.rs:355:23" }, location: Location { file: "/runner/_work/lance/lance/rust/lance-namespace-impls/src/dir/manifest.rs", line: 169, column: 31 } }
python/tests/test_namespace_rest.py::TestTableOperations::test_register_table_rejects_absolute_path 
[FIXTURE] Creating RestAdapter with tmpdir=/tmp/tmpwvbvbg_7, port=13055
[FIXTURE] RestAdapter context entered, creating client
[FIXTURE] Client created, yielding
FAILED[FIXTURE] Test completed, cleaning up
```

Basically the server of last test was still active, thus the new server fails to start and the client still calls into the old server.

File: java/lance-jni/src/namespace.rs [hunk 1]
```diff
@@ -1322,7 +1312,8 @@ pub extern "system" fn Java_org_lance_namespace_RestAdapter_stop(
     let adapter = unsafe { &mut *(handle as *mut BlockingRestAdapter) };
 
     if let Some(server_handle) = adapter.server_handle.take() {
-        server_handle.abort();
+        server_handle.shutdown();
+        std::thread::sleep(std::time::Duration::from_millis(100));
```
Comment (westonpace) [inline java/lance-jni/src/namespace.rs]: Can we add a comment about why this sleep is needed?

File: java/src/test/java/org/lance/namespace/RestNamespaceTest.java [hunk 2]
```diff
@@ -57,8 +57,7 @@ public class RestNamespaceTest {
   void setUp() {
     allocator = new RootAllocator(Long.MAX_VALUE);
 
-    // Use a random port to avoid conflicts
-    port = 4000 + new Random().nextInt(10000);
+    port = 10000 + new Random().nextInt(10000);
```
Comment (westonpace) [inline java/src/test/java/org/lance/namespace/RestNamespaceTest.java]: I suspect you already know but the canonical solution to this problem that I'm used to seeing is to use port number 0 and have that pass all the way down to the socket opening.  Then the OS will assign a random ephemeral port and you can either return that from the constructor or make it available via an accessor.

Not sure if that is easily doable or possible but figured I'd mention it.

File: rust/lance-namespace-impls/src/rest_adapter.rs [hunk 3]
```diff
@@ -76,24 +77,57 @@ impl RestAdapter {
...
+/// Use this handle to gracefully shut down the server when it's no longer needed.
+pub struct RestAdapterHandle {
+    shutdown_tx: watch::Sender<bool>,
+}
+
+impl RestAdapterHandle {
+    /// Gracefully shut down the server.
+    ///
+    /// This signals the server to stop accepting new connections and wait for
+    /// existing connections to complete.
```
Comment (westonpace) [inline rust/lance-namespace-impls/src/rest_adapter.rs]: This method doesn't actually block until the shutdown is complete though right?  I feel like we should document that fact (or ideally find some way to block?)
