### PR TITLE
fix: do not panic when performing a pushdown scan on a multi-data-file fragment

### LINKED ISSUE #1871: Panic when scanning a dataset that has multi-data-file fragments
To reproduce you need to create a dataset that has a fragment with more than one data file (e.g. by doing a merge).  Then scan this dataset and give a projection that completely avoids one of the data files.  We appear to still create a file reader for the data file and that file reader panics because it isn't loading the row id or any data.

### PR DESCRIPTION
**Pull request by westonpace**
The normal scan algorithm is:

```
open fragment reader with projected schema
for batch in batches:
  scan batch
```

The pushdown algorithm is:

```
open fragment with full schema
for batch, simplified_projection in filter(batches):
  projected scan batch(simplified_projection)
```

This means that the data files that need to be read could change from batch to batch.  This was not previously being accounted for and now it is.

Closes #1871

### CODE REVIEW

File: rust/lance/src/dataset/fragment.rs [hunk 1]
```diff
@@ -861,17 +861,32 @@ impl FragmentReader {
...
-                    .read_batch(
-                        batch_id as i32,
-                        params,
-                        &projection?,
-                        self.deletion_vec.as_ref().map(|dv| dv.as_ref()),
-                    )
-                    .await
+                // Apply ? inside the task to keep read_tasks a simple iter of futures
+                // for try_join_all
+                let projection = projection?;
```
Comment (eddyxu) [inline rust/lance/src/dataset/fragment.rs:866]: Does `reader` open a file descriptor? If so, should we handle such case during the construction of reader?

Comment (westonpace) [reply rust/lance/src/dataset/fragment.rs:866]: It does.  We could probably also fix that.  I'll give it a shot.  We need both cases handled though so we will still need this change.

For example, the filter might be `x < 20 AND y < 10`.  From statistics, we might learn that, for batch 7, `x < 20` is always true, and so we don't need to read that column.  Then we would just read column `y` just for that batch.  In this case we do need to open both readers but we need to account for the readers required changing from batch to batch still.

Comment (eddyxu) [reply rust/lance/src/dataset/fragment.rs:866]: I see.

**Review by eddyxu — APPROVED** [review]
Thanks @westonpace
