### PR TITLE
fix!: delta index fragment bitmaps contained previous index coverage

### LINKED ISSUE #3374: Delta indices have wrong fragment bitmap
Creating a delta index produces overlapping fragment bitmaps. It's not obvious whether this is just a bug in metadata, or it's actually not producing a correct delta.

```python
import lance
import pyarrow as pa
import pyarrow.compute as pc

assert lance.__version__ == '0.21.0'

data = pa.table({
    'vector': pa.FixedSizeListArray.from_arrays(
        pc.random(32 * 1024).cast(pa.float32()),
        32
    )
})
ds = lance.write_dataset(data, 'memory://')
ds.create_index('vector', index_type="IVF_PQ", num_partitions=1, num_sub_vectors=2)
ds.list_indices()
```

```
[{'name': 'vector_idx',
  'type': 'IVF_PQ',
  'uuid': '2e67e9ed-3bae-44a0-bf91-7b2a08ab7aff',
  'fields': ['vector'],
  'version': 1,
  'fragment_ids': {0}}]
```

```python
data2 = pa.table({
    'vector': pa.FixedSizeListArray.from_arrays(
        pc.random(32 * 1024).cast(pa.float32()),
        32
    )
})
ds.insert(data2)
ds.optimize.optimize_indices(num_indices_to_merge=0)
ds.list_indices()
```

```
[{'name': 'vector_idx',
  'type': 'IVF_PQ',
  'uuid': '2e67e9ed-3bae-44a0-bf91-7b2a08ab7aff',
  'fields': ['vector'],
  'version': 1,
  'fragment_ids': {0}},
 {'name': 'vector_idx',
  'type': 'IVF_PQ',
  'uuid': '6d711d5f-30d8-40b9-afb5-ec869fa92be9',
  'fields': ['vector'],
  'version': 3,
  'fragment_ids': {0, 1}}]
```

### PR DESCRIPTION
**Pull request by wjones127**
BREAKING CHANGE: delta index fragment bitmaps will now only contain the fragment ids covered by the delta, not the full index. To get the full bitmap, make sure to union with all index segments with the same name. Old datasets will still show previous fragment ids, until a write is done, which forces a migration. **If corrupted fragment ids are present in a dataset, then the `dataset.index_statistics` will return an error. Before using `dataset.index_statistics()`, call `dataset.validate()` to check the integrity and use `dataset.delete("false")` to force a migration.**

Fixes #3374

### CODE REVIEW

File: rust/lance/src/index.rs [hunk 1]
```diff
@@ -570,7 +570,7 @@ impl DatasetIndexExt for Dataset {
             .len();
 
         let num_unindexed_fragments = self.fragments().len() - num_indexed_fragments;
-        let num_indexed_rows = num_indexed_rows_per_delta.iter().last().unwrap();
+        let num_indexed_rows: usize = num_indexed_rows_per_delta.iter().cloned().sum();
```
Comment (wjones127) [inline rust/lance/src/index.rs:573]: @chebbyChefNEQ I saw you wrote `.last()` in #2979. Do you remember why this made sense to you at the time?

Comment (chebbyChefNEQ) [reply rust/lance/src/index.rs:573]: `num_indexed_rows_per_delta` is a vec of cumulative number of rows indexed I think. so we get a vec like
[100, 150, 200] instead of `[100, 50, 50]`

Comment (chebbyChefNEQ) [reply rust/lance/src/index.rs:573]: so `.last()` is the total number of indexed rows

Comment (wjones127) [reply rust/lance/src/index.rs:573]: Was it intentional that it was cumulative? I have been treating it as a bug in this PR

Comment (chebbyChefNEQ) [reply rust/lance/src/index.rs:573]: I'm not sure. I don't think we ever made a contract around this. I agree that cumulative seems like a bug and we should record the number of indexed rows per delta

**Review by westonpace — APPROVED** [review]
Thanks for working through this
